Repository AY2425S2-CS2103-F15-1/tp, pull requests merged in 2025-03, with the labels that each got.

#23 Update AboutUs page with @victoria281 details
  docs/AboutUs.md
  docs/images/victoria281.png
  docs/team/victoria281.md
Labels: type.Task

#24 Update AboutUs
  docs/AboutUs.md
  docs/team/anafterthought.md
Labels: type.Task

#32 Add Glossary to Dev Guide
  docs/DeveloperGuide.md
Labels: type.Task

#34 Update site-wide settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task

#62 Add "add tutorial" command
  src/main/java/seedu/address/logic/commands/AddTutorialCommand.java
  src/main/java/seedu/address/logic/commands/TutorialCommand.java
  src/main/java/seedu/address/logic/parser/AddTutorialCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/TutorialParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsInclTutorials.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#69 Add list tutorial command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddTutorialCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListTutorialCommand.java
  src/main/java/seedu/address/logic/parser/ListTutorialCommandParser.java
  src/main/java/seedu/address/logic/parser/TutorialParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/NavigationMode.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TutorialCard.java
  src/main/java/seedu/address/ui/TutorialListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/TutorialListCard.fxml
  src/main/resources/view/TutorialListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListTutorialCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task

#77 Add User Guide for `tutorial list` command
  docs/UserGuide.md
Labels: type.Task

#104 Fix missing bracket in `edit` help
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Bug

#108 Default tutorials added to SampleDataUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsInclTutorials.json
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: type.Bug

#113 Remove error for extraneous parameters in `tutorial list` command
  src/main/java/seedu/address/logic/parser/ListTutorialCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug

#128 Remove print statement from `StudentListPanel`
  src/main/java/seedu/address/ui/StudentListPanel.java
Labels: type.Bug

#126 Update help page User Guide URL
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug

#170 Rename Window title to TAskbook
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#167 Implement stateful Navigation Mode
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/commons/core/GuiSettingsTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Enhancement

#208 Rename occurrences of `person` to `student` to maintain consistency
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/student-related/EditStudentSequenceDiagram.puml
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/student-related/EditStudentSequenceDiagram.svg
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddStudentToTutorialCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteStudentFromTutorialCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/student/exceptions/StudentNotFoundException.java
  src/main/java/seedu/address/storage/json/JsonSerializableAddressBook.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsInclTutorials.json
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddTutorialCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/storage/json/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task
